;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #66
background-alt = #0000
foreground = #dfdfdf
foreground-alt = #555
primary = #00ff7f
secondary = #e60053
alert = #bd2c40
disabled = #707880
red = #fc7b81
blue = #075b93
green = #00ff7f
cyan = #90daff
magenta = #e2a6ff
og_green = #00FF00
reddish_orange = #FF5349
black = #ffffff

[bar/bar]
monitor=${env:MONITOR:}
width = 100%
height = 24pt
radius = 6 

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 4pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = monospace;2
font-1 = "fontawesome-regular:size=16;4"

modules-left = i3 
modules-center = xwindow
modules-right = pulseaudio memory filesystem xkeyboard popup-calendar updates-pacman-aurhelper

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

tray-position = right

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

;[module/xworkspaces]
;type = internal/xworkspaces

;label-active = %name%
;label-active-background = ${colors.background-alt}
;label-active-underline= ${colors.primary}
;label-active-padding = 1

;label-occupied = %name%
;label-occupied-padding = 1

;label-urgent = %name%
;label-urgent-background = ${colors.alert}
;label-urgent-padding = 1

;label-empty = %name%
;label-empty-foreground = ${colors.disabled}
;label-empty-padding = 1

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

; Only show workspaces on the same output as the bar
pin-workspaces = true

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}

; focused = Active workspace on focused monitor
label-focused = %index%
label-focused-background = ${colors.background}
label-focused-underline = ${module/bspwm.label-focused-underline}
label-focused-padding = ${module/bspwm.label-focused-padding}

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-padding = ${module/bspwm.label-occupied-padding}

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-background = ${module/bspwm.label-urgent-background}
label-urgent-padding = ${module/bspwm.label-urgent-padding}

[module/bspwm]
type = internal/bspwm

label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.green}
label-focused-padding = 2

label-occupied = %index%
label-occupied-padding = 2

label-urgent = %index%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

label-empty = %index%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 2

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

format-foreground = ${colors.green}

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /home

label-mounted = "%{F#00ff7f}%{F-} %free%"

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

label-background = ${module/bspwm.label-focused-background}
label-mounted-underline = ${module/bspwm.label-focused-background} 

[module/pulseaudio]
type = internal/pulseaudio

; Sink to be used, if it exists (find using `pacmd list-sinks`, name field)
; If not, uses default sink
sink = alsa_output.pci-0000_12_00.3.analog-stereo

; Use PA_VOLUME_UI_MAX (~153%) if true, or PA_VOLUME_NORM (100%) if false
; Default: true
use-ui-max = true

; Interval for volume increase/decrease (in percent points)
; Default: 5
interval = 5

; Right and Middle click
click = pavucontrol
click-right = pavucontrol

format-volume = %{F#00ff7f}<ramp-volume>%{F-} <label-volume> 

format-muted = <label-muted>

label-volume = %percentage%%

label-muted =  0%
label-muted-foreground = #FD0105

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}

label = %percentage_used%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/date]
type = internal/date
interval = 3 

date = "%d %b"
time = "%H:%M"

format-prefix-foreground = ${colors.foreground-alt}

label = %date% %time%
label-foreground = ${colors.primary}

[module/popup-calendar]
type = custom/script
exec = ~/.config/polybar/scripts/popup-calendar.sh
interval = 5
click-left = ~/.config/polybar/scripts/popup-calendar.sh --popup &

format-prefix-foreground = ${colors.foreground-alt}

label-foreground = ${colors.primary}

[module/updates-pacman-aurhelper]
type = custom/script
exec = ~/.config/polybar/scripts/updates-pacman-aur.sh
interval = 600

format-prefix-foreground= ${colors.foreground-alt}

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
