;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #66
background-alt = #0000
foreground = #dfdfdf
foreground-alt = #555
primary = #00ff7f
secondary = #e60053
alert = #bd2c40
disabled = #707880
red = #fc7b81
blue = #075b93
green = #00ff7f
cyan = #90daff
magenta = #e2a6ff
og_green = #00FF00
reddish_orange = #FF5349
black = #ffffff

[bar/bar]
monitor=${env:MONITOR:}
width = 100%
height = 24pt
radius = 6 

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 4pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = monospace;2
font-1 = "fontawesome-regular:size=16;4"

modules-left = i3 
modules-center = xwindow
modules-right = pulseaudio xkeyboard battery popup-calendar

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

tray-position = right

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

; Only show workspaces on the same output as the bar
pin-workspaces = true

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.primary}

; focused = Active workspace on focused monitor
label-focused = %index%
label-focused-background = ${colors.background}
label-focused-underline = ${colors.green}
label-focused-padding = 2

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-padding = 2

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

format-foreground = ${colors.green}

[module/pulseaudio]
type = internal/pulseaudio

use-ui-max = true

; Interval for volume increase/decrease (in percent points)
interval = 5

; Right and Middle click
click = pavucontrol
click-right = pavucontrol

format-muted = <label-muted>

label-volume = "%percentage%%"
label-foreground = ${colors.green}

label-muted = 0%
label-muted-foreground = #FD0105

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

#TODO
[module/memory]
type = custom/script
exec = ~/.config/polybar/scripts/memory.sh
interval = 2

format-prefix = "mem: "
format-prefix-foreground = ${colors.primary}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU:"
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[module/battery]
type = custom/script
exec = ~/.config/polybar/scripts/battery.sh
interval = 10

format-prefix = "bat "
format-prefix-foreground = ${colors.primary}

[module/storage]
type = custom/script
exec = ~/.config/polybar/scripts/storage.sh
interval = 30

format-prefix = "home:"
format-prefix-foreground = ${colors.primary}

[module/popup-calendar]
type = custom/script
exec = ~/.config/polybar/scripts/popup-calendar.sh
interval = 5
click-left = ~/.config/polybar/scripts/popup-calendar.sh --popup &

format-prefix-foreground = ${colors.foreground-alt}

label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
